sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - flake8
  # TODO: Replace with an actual test suite:
  # https://github.com/kennethreitz/bob-builder/issues/31
  - bob --help
matrix:
  allow_failures:
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
  fast_finish: true
